SRC_FILE    = \
	    celem.F90 \
	    DPGLaser.F \
	    problem.F \
            dirichlet.F90 \
            elem.F \
            elem_residual.F \
	    exact.F90 \
	    fake.F90 \
	    finalize.F90 \
	    getf.F90 \
            initialize.F90 \
            main.F90 \
            set_initial_mesh.F90 \
	    set_mesh_refinement.F90 \
	    soldis.F90 \
            my_tests.F \
            adapt_DPG.F \
            compute_BC_interp_error.F








